# -*- coding: utf-8 -*-
"""Dog_Breed

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln8tTgLelFa31Na4AHPXtozkZ39nz5Cp
"""

from google.colab import files
files.upload()

!pip install -q kaggle

# The Kaggle API client expects this file to be in ~/.kaggle, so move it there.
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

# This permissions change avoids a warning on Kaggle tool startup.
!chmod 600 ~/.kaggle/kaggle.json

# Commented out IPython magic to ensure Python compatibility.
# Creating directory and changing the current working directory
!mkdir dog_dataset
# %cd dog_dataset

# Searching for dataset
!kaggle datasets list -s dogbreedidfromcomp

# Commented out IPython magic to ensure Python compatibility.
!kaggle datasets download catherinehorng/dogbreedidfromcomp
# %cd ..

# Unzipping downloaded file and removing unusable file
!unzip dog_dataset/dogbreedidfromcomp.zip -d dog_dataset
!rm dog_dataset/dogbreedidfromcomp.zip
!rm dog_dataset/sample_submission.csv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing  import LabelBinarizer
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from keras.preprocessing import image
from keras.models import Sequential
from keras.layers import Dense,Dropout,MaxPool2D,Conv2D,Flatten
from keras.optimizers import Adam

labels_df = pd.read_csv('dog_dataset/labels.csv')
display(labels_df.head())

breed_all=labels_df['breed']
breed_count=breed_all.value_counts()
breed_count.head()

Class_names=['scottish_deerhound','maltese_dog','afghan_hound','entlebucher']
labels=labels_df[labels_df['breed'].isin(Class_names)]
labels=labels.reset_index()
labels.head()

X_Data=np.zeros((len(labels),224,224,3),dtype='float32')
Y_Data=LabelBinarizer().fit_transform(labels['breed'])
for i in tqdm(range(len(labels))):
  img=image.load_img('dog_dataset/train/%s.jpg' %labels['id'][i], target_size=(224,224))
  img=image.img_to_array(img)
  x=np.expand_dims(img.copy(),axis=0)
  X_Data[i]=x/255.0

print('\nTrain Images shape: ',X_Data.shape,' size: {:,}'.format(X_Data.size))
print('One-hot encoded output shape: ',Y_Data.shape,' size: {:,}'.format(Y_Data.size))

model=Sequential()
model.add(Conv2D(filters=64,kernel_size = (5,5), activation='relu', input_shape=(224,224,3)))
model.add(MaxPool2D(pool_size =(2,2)))

model.add(Conv2D(filters=32,kernel_size = (7,7), activation='relu',kernel_regularizer='l2'))
model.add(MaxPool2D(pool_size= (2,2)))

model.add(Conv2D(filters=16,kernel_size=(3,3), activation='relu',kernel_regularizer='l2'))
model.add(MaxPool2D(pool_size= (2,2)))

model.add(Conv2D(filters=8,kernel_size=(5,5), activation='relu',kernel_regularizer='l2'))
model.add(MaxPool2D(pool_size= (2,2)))

model.add(Flatten())
model.add(Dense(128,activation='relu',kernel_regularizer='l2'))
model.add(Dense(64,activation='relu',kernel_regularizer='l2'))
model.add(Dense(32,activation='relu',kernel_regularizer='l2'))
model.add(Dense(len(Class_names),activation='softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = Adam(0.0001),metrics=['accuracy'])

model.summary()

X_train_and_val, X_test, Y_train_and_val, Y_test = train_test_split(X_Data, Y_Data, test_size = 0.1)

X_train, X_val, Y_train, Y_val = train_test_split(X_train_and_val, Y_train_and_val, test_size = 0.2)

epochs = 100
batch_size = 128
history = model.fit(X_train, Y_train, batch_size = batch_size, epochs = epochs,validation_data = (X_val, Y_val))

# Plot the training history
plt.figure(figsize=(12, 5))
plt.plot(history.history['accuracy'], color='r')
plt.plot(history.history['val_accuracy'], color='b')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epochs')
plt.legend(['train', 'val'])

plt.show()

Y_pred = model.predict(X_test)
score = model.evaluate(X_test, Y_test)
print('Accuracy over the test set: \n ', round((score[1]*100), 2), '%')

# Plotting image to compare
plt.imshow(X_test[1,:,:,:])
plt.show()

# Finding max value from predition list and comaparing original value vs predicted
print("Originally : ",labels['breed'][np.argmax(Y_test[1])])
print("Predicted : ",labels['breed'][np.argmax(Y_pred[1])])